<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQjxRSOx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQjxRSOx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQjxRSOx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQjxRSOx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQjxRSOx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QjxRSOx',
    'container.build_id' => '129bfaad',
    'container.build_time' => 1574165122,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQjxRSOx');
